### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by epic6969** [HackerPolice/MissedIT#20]
when i do ./load the game freezes completely then crashes
same thing with fuzion (https://github.com/LWSS/Fuzion/issues/621)

**Comment by tutoraddicts** [comment]
Can you try injecting this [repo](https://github.com/HackerPolice/HantaHook-linux) and see if it is crashing or not.

and mention your GCC and Cmake Version. i am not sure if it is not related to kernel|driver need to debug

**Comment by epic6969** [comment]
> Can you try injecting this [repo](https://github.com/HackerPolice/HantaHook-linux) and see if it is crashing or not.
> 
> and mention your GCC and Cmake Version. i am not sure if it is not related to kernel|driver need to debug

crashed

**Comment by tutoraddicts** [comment]
As I can see in other comments that it is happening after the last update. check for the changelog and see what it updates in the last update.

**Comment by epic6969** [comment]
Fix: https://github.com/LWSS/Fuzion/issues/621#issuecomment-777815272
