### ISSUE TITLE
GUI settings not working & crashing

### ISSUE THREAD

**Issue by AndreasYNY** [HackerPolice/MissedIT#21]
after update this is no longer working & crashing at some point...
is there any fix to this?
thanks!

Legitbot not working: 
![2021-03-19 17-59-20](https://user-images.githubusercontent.com/46004308/111770634-3dbeda80-88dd-11eb-81a3-d91db3cd738e.gif)

Ragebot crashing: 
![2021-03-19 17-56-06](https://user-images.githubusercontent.com/46004308/111770650-41526180-88dd-11eb-954a-05211b74293c.gif)

**Comment by tutoraddicts** [comment]
Try using Aimware V5 menu in left corner

**Comment by tutoraddicts** [comment]
DO not use backtrack in ragebot

**Comment by AndreasYNY** [comment]
it's still the same, aimware v5 menu/ legacy, its still have the same problem.
i don't have anything on all you see in the gif is all i have on.

**Comment by tutoraddicts** [comment]
Fixed
