### ISSUE TITLE
Game feels like it's capped at 60fps?

### ISSUE THREAD

**Issue by AdverseMiller** [HackerPolice/MissedIT#23]
I'm running arch linux and before I inject the cheat, my frame rate feels normal but after I inject it feels like I'm capped at 60FPS even though my frame rate is unlimited. It seems like it adds some sort of motion blur or V-sync.

**Comment by tutoraddicts** [comment]
Though It should not but I will look over it, it will be great if you share some screenshots over problems will be helpful.
