### ISSUE TITLE
New update for operating riptide completely breaks the cheat.

### ISSUE THREAD

**Issue by AdverseMiller** [HackerPolice/MissedIT#25]
The newly released operation riptide will cause the cheat to crash when using it in game. I've tried many different configs and even just having the cheat injected with no config selected will still cause the cheat to crash. I've noticed this to happen with multiple other AImtux based cheats.

**Comment by hexdecimal16** [comment]
Same here dude

**Comment by tutoraddicts** [comment]
Will see
