### ISSUE TITLE
Your GCC seems outdated.

### ISSUE THREAD

**Issue by krmkcbs** [HackerPolice/MissedIT#7]
-- The C compiler identification is GNU 6.5.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (message):
  Your GCC seems outdated.  Go to
  https://github.com/AimTuxOfficial/AimTux/wiki/Updating-your-compiler for
  further instructions.  If you have done so and still see this message, run
  'git clean -fdx' and try again

-- Configuring incomplete, errors occurred!
See also "/home/krmkcbs/MissedIT/CMakeFiles/CMakeOutput.log".

i am getting this error when compiling :(
i have done the instructions too, idk what the problem is at this point
normal Fuzion works - builds fine
my distro is KDE Neon

**Comment by krmkcbs** [comment]
(this error happens on the master and alfa branches)

**Comment by krmkcbs** [comment]
fixed the issue,
i fixed it by making  if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 7.0) in the cmakelists.txt to this  if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0)

**Comment by tutoraddicts** [comment]
Nice dude
